// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7rbP4XvwNjMALEdZd2ZzoKskKiGzksA',
    appId: '1:889050351816:web:a1fe24fbfb6f97294ffdfd',
    messagingSenderId: '889050351816',
    projectId: 'quizx-64d66',
    authDomain: 'quizx-64d66.firebaseapp.com',
    storageBucket: 'quizx-64d66.firebasestorage.app',
    measurementId: 'G-1MT7Q7FFP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbCxQAr5wtDfvxiJPSxaD5uw151YC1ofU',
    appId: '1:889050351816:android:7f2a1903ff8392814ffdfd',
    messagingSenderId: '889050351816',
    projectId: 'quizx-64d66',
    storageBucket: 'quizx-64d66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7sW0xG5GU6MqqAxsM15o1v9vmKA-WTU',
    appId: '1:889050351816:ios:b9d630b90f0b08be4ffdfd',
    messagingSenderId: '889050351816',
    projectId: 'quizx-64d66',
    storageBucket: 'quizx-64d66.firebasestorage.app',
    iosBundleId: 'com.example.quizBattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD7sW0xG5GU6MqqAxsM15o1v9vmKA-WTU',
    appId: '1:889050351816:ios:b9d630b90f0b08be4ffdfd',
    messagingSenderId: '889050351816',
    projectId: 'quizx-64d66',
    storageBucket: 'quizx-64d66.firebasestorage.app',
    iosBundleId: 'com.example.quizBattle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY7rbP4XvwNjMALEdZd2ZzoKskKiGzksA',
    appId: '1:889050351816:web:5a1e72600010a0ee4ffdfd',
    messagingSenderId: '889050351816',
    projectId: 'quizx-64d66',
    authDomain: 'quizx-64d66.firebaseapp.com',
    storageBucket: 'quizx-64d66.firebasestorage.app',
    measurementId: 'G-PEQDL9B5NE',
  );
}
